export const CHANGE_COUNT_ADD = "CHANGE_COUNT_ADD";
export const CHANGE_COUNT_DELETE = "CHANGE_COUNT_DELETE";
export const CHANGE_COUNT_DELETE_ALL = "CHANGE_COUNT_DELETE_ALL";
export const CHANGE_COUNT_CLEAR_BASKET = "CHANGE_COUNT_CLEAR_BASKET";
export const CHANGE_VALUE = "CHANGE_VALUE";
